language: node_js
node_js:
    - 14

jobs:
    include:
        - stage: test
          install: "npm install"
          script: "npm run test"

        - stage: report-coverage
          if: branch = master
          install: "npm install"
          script: "npm run coverage"
