language: node_js
node_js:
    - 14

jobs:
    include:
        - stage: test
          if: branch != master
          install: "npm install"
          script: "npm run test"

        - stage: test-with-coverage
          if: branch = master
          install: "npm install"
          script: "npm run test:ci"
          after_success: "npm run coverage"
