name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      node_version: 16.14.x
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node ${{ env.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node_version }}

      - name: Install
        run: npm install

      - name: Compile
        run: npm run compile

      - name: Test
        run: npm test

      - name: Build
        run: npm run build

  coverage:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    env:
      node_version: 16.14.x
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node ${{ env.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node_version }}

      - name: Install
        run: npm install

      - name: Report coverage
        run: |
          npm run test:ci
          npm run coverage
